# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -yq python3.8 python3-pip
    pip3 install psycopg2
    pip3 install Django
  SHELL
 
  config.vm.provision "file", source: "../empty_file", destination: "empty_file"
end
